// Code generated by ifacemaker; DO NOT EDIT.

package controller

import (
	"context"

	"github.com/anoideaopen/token/model"
)

// Controller describes methods, implemented by the service package.
type Notification interface {
	// NotifyBalancesUpdate добавляет новую запись в бухгалтерскую книгу, о движении средств
	// пользователя или пользователей. Записи валидируются перед сохранением.
	NotifyBalancesUpdate(ctx context.Context, bu model.Notification[model.BalancesUpdate]) error
}
