// Code generated by ifacemaker; DO NOT EDIT.

package repository

import (
	"context"

	"github.com/anoideaopen/token/model"
)

// Repository describes methods, implemented by the storage package.
type Notification interface {
	// SaveBalancesUpdate stores notification record to the notification database.
	SaveBalancesUpdate(ctx context.Context, bu model.Notification[model.BalancesUpdate]) error
}
